### ISSUE TITLE
TG-2022-1Levantamentos Iniciais

### ISSUE THREAD

**Issue by ProfVerissimoFatec** [alinesc/YAD188-G05-GerenciamentoQuimicos#1]
# Objetivo
* Descrevam aqui:
    * Tema do trabalho (exemplo: App para adoção de PETs"
    * Breve descrição da situação problema (exemplo: Desenvolver um app para facilitar a adoção de Pets, tendo  como objetivo subjacente a criação de uma rede social com pessoas interessadas em cuidar de animais de estimação)
 
# Artefatos
Deverá ser postado **um arquivo**, formato PDF, cujo conteúdo deverá ter:
* Scrum Master 
    * Nome
    *  Responsabilidades
* Product Owner
    * Nome
    * Responsabilidades 
* Development Time
    Nome | papel | Responsabilidade 
    --------| ------ |--------------------
     xxx      |          |                               
     yyy      |          |                              
     zzz      |          |

**Comment by alinesc** [comment]
[LevantamentosIniciais.pdf](https://github.com/alinesc/YAD188-G05-GerenciamentoQuimicos/files/8218930/LevantamentosIniciais.pdf)

Tema do trabalho: Sistema de Gerenciamento de Produtos Químicos
Descrição: Desenvolvimento de software para gerenciamento de produtos químicos, armazenados em instituições de ensino e pesquisa.

**Comment by ProfVerissimoFatec** [comment]
Aline, boa noite
OK Tarefa cumprida com sucesso
Obrigado

**Comment by ProfVerissimoFatec** [comment]
Concluido OK

**Comment by ProfVerissimoFatec** [comment]
.
